### ISSUE TITLE
Python error on launch

### ISSUE THREAD

**Issue by canredist** [johnpholden/qgis3redistricter#11]
I get the following error when intitating Redistricter after installing it with QGIS 3.24 Tisler; the plugin launches, I go to create a new redistricting plan, click on OK and this pops up, the plugin will not create a new plan and will not proceed.

TypeError: int() argument must be a string, a bytes-like object or a number, not 'QVariant' 
Traceback (most recent call last):
  File "C:\Users/bjwig/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis3redistricter-master\StattoRedistrict.py", line 2282, in updatePanelAndSaveParameters
    self.saveParameters()
  File "C:\Users/bjwig/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis3redistricter-master\StattoRedistrict.py", line 1307, in saveParameters
    self.totalpop = self.totalpop + int(feature[self.popfield])

**Comment by johnpholden** [comment]
Your redistricting plan's population field is not a number. You probably have a missing or blank value in the column somewhere.

**Comment by johnpholden** [comment]
The next edition should throw an error message. Will update on github once it's confirmed stable.
