### ISSUE TITLE
Python error launching plugin

### ISSUE THREAD

**Issue by canredist** [johnpholden/qgis3redistricter#12]
After installing the plugin in QGIs and creaing a new redistricting plan, I click on OK and get the following error; the plugin launches but does not proceed and will not work:

TypeError: int() argument must be a string, a bytes-like object or a number, not 'QVariant' 
Traceback (most recent call last):
  File "C:\Users/bjwig/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis3redistricter-master\StattoRedistrict.py", line 2282, in updatePanelAndSaveParameters
    self.saveParameters()
  File "C:\Users/bjwig/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis3redistricter-master\StattoRedistrict.py", line 1307, in saveParameters
    self.totalpop = self.totalpop + int(feature[self.popfield])

**Comment by canredist** [comment]
Resolved.  Population Data is not a number in one field.
